version: "3"
services:
  db:
    container_name: db
    env_file: ./.env
    build:
      context: .
      dockerfile: ./Dockerfile-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: ${TZ}
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - mlnet

  jupyter:
    container_name: jupyter
    build:
      context: .
      dockerfile: ./Dockerfile-jupyter
    depends_on:
      - db
    volumes:
      - .:/home/jovyan
    ports:
      - "8888:8888"
    networks:
      - mlnet

volumes:
  pg_data:
    driver: local

networks:
  mlnet:
    driver: bridge
